#!/usr/bin/perl
use strict;
use warnings;

use FindBin;
use lib ("$FindBin::Bin/../lib", "$FindBin::Bin/../extlib");

use File::Spec;
use MT;

use lib File::Spec->catfile(MT->instance->component('ObjectClone')->path, 'lib');

use MT::Tool::ObjectClone;
MT::Tool::ObjectClone->main(@_);
